export const DishCategoryEnum = {
  SOUP: "Soup",
  MAIN: "Main",
  SNACK: "Snack",
  SALAD: "Salad",
  SAUCE: "Sauce",
  DESSERT: "Dessert",
  BAKERY: "Bakery",
  DRINK: "Drink",
  PRESERVATION: "Preservation",
};

export const DishSubCategoryEnum = {
  Soup: "Soup",
  "Main-Meat": "Main-Meat",
  "Main-Fish": "Main-Fish",
  "Main-Vegetarian": "Main-Vegetarian",
  "Snack-Cold": "Snack-Cold",
  "Snack-Hot": "Snack-Hot",
  "Snack-Canape": "Snack-Canape",
  "Salad-Vegetable": "Salad-Vegetable",
  "Salad-Meat": "Salad-Meat",
  "Salad-Fruit": "Salad-Fruit",
  "Sauce-Meat": "Sauce-Meat",
  "Sauce-Fish": "Sauce-Fish",
  "Sauce-Salad": "Sauce-Salad",
  Dessert: "Dessert",
  "Bakery-Cakes": "Bakery-Cakes",
  "Bakery-Cookies": "Bakery-Cookies",
  "Bakery-Pies": "Baker -Pies",
  "Drink-Alcoholic": "Drink-Alcoholic",
  "Drink-Non": "Drink-Non-Alcoholic",
  "Preservation-Fruit": "Preservation-Fruit",
  "Preservation-Vegetable": "Preservation-Vegetable",
};
